//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentAgency.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public int LogId { get; set; }
        public int UserId { get; set; }
        public int ActionId { get; set; }
        public System.DateTime ActionDateTime { get; set; }
        public string Details { get; set; }
        public string IpAddress { get; set; }
    
        public virtual AuditActions AuditActions { get; set; }
        public virtual Users Users { get; set; }
    }
}
