//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentAgency.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backups
    {
        public int BackupId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int LocationId { get; set; }
        public string FileName { get; set; }
        public Nullable<decimal> SizeMB { get; set; }
        public bool IsSuccessful { get; set; }
    
        public virtual BackupLocations BackupLocations { get; set; }
        public virtual Users Users { get; set; }
    }
}
