//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentAgency.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContacts
    {
        public int ContactId { get; set; }
        public int ClientId { get; set; }
        public int ContactTypeId { get; set; }
        public string ContactValue { get; set; }
        public string ContactPerson { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ContactTypes ContactTypes { get; set; }
    }
}
